<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Additional Compiled Classes
	|--------------------------------------------------------------------------
	|
	| Here you may specify additional classes to include in the compiled file
	| generated by the `artisan optimize` command. These should be classes
	| that are included on basically every request into the application.
	|
	*/

	'vendor/laravel/framework/src/Illuminate/Support/Collection.php',
	'vendor/laravel/framework/src/Illuminate/Database/*',
    'vendor/zizaco/entrust/src/Entrust/*.php',
    'app/library/HelperClass.php',



);