<?php

return [

    'DISTRICT_ID' => '1',
    'DISTRICT_NAME' => 'WAKISO',
    'FACILITY_LEVEL_ID' => '2',
    'FACILITY_ID' => '1',
    'FACILITY_NAME' => 'ENTEBBE GENERAL HOSPITAL LABORATORY',
    'FACILITY_CODE' => 'ENTB01',
    'FACILITY_OWNERSHIP_ID' => '1',
    'FIN_YEAR_ID' => '1',
    'FIN_YEAR_NAME' => '2018/2019',
    'INCOMING_STOCK_FLAG' => 'I',
    'OUTGOING_STOCK_FLAG' => 'O',
    'LOSSES_ADJUSTMENTS_STOCK_FLAG' => 'A',
    'FROM_FACILITY' => '1',
    'FROM_WAREHOUSE' => '2',
    'TO_FACILITY' => '3',
    'TO_PERSON' => '4',
    ];
