<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Whoops' => array($vendorDir . '/filp/whoops/src'),
    'System' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Stack' => array($vendorDir . '/stack/builder/src'),
    'Predis' => array($vendorDir . '/predis/predis/lib'),
    'PHPParser' => array($vendorDir . '/nikic/php-parser/lib'),
    'Net' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Math' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'LaravelBook\\Ardent' => array($vendorDir . '/laravelbook/ardent/src'),
    'Jeremeamia\\SuperClosure' => array($vendorDir . '/jeremeamia/SuperClosure/src'),
    'Illuminate' => array($vendorDir . '/laravel/framework/src'),
    'File' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Crypt' => array($vendorDir . '/phpseclib/phpseclib/phpseclib'),
    'ClassPreloader' => array($vendorDir . '/classpreloader/classpreloader/src'),
    'Boris' => array($vendorDir . '/d11wtq/boris/lib'),
);
